server:
  port: 9008
spring:
  application:
    name: ten-user
  jackson:
    default-property-inclusion: non_null  #s 过滤响应时候的空字段,不在前端显示
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.237.3:3306/tensquare_user?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  rabbitmq:
    host: 120.27.237.3
    port: 5672
    username: guest
    password: guest
  redis:
    host: 120.27.237.3

jwt:
  config:
    # 盐
    key: wenting
    # 过期时间一小时
    ttl: 3600000

mybatis:
  mapper-locations: classpath:/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
    registry-fetch-interval-seconds: 5
    # 是否将自己注册进eureka
    register-with-eureka: true
    # 是否从eureka中获取信息
    fetch-registry: true
  instance:
    # 发现ip
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

